/**
 * reader-ids.test.ts — a guard on the shape of the event ids the page reader
 * builds (N.97, ruled by Dann 2026-08-24).
 *
 * WHY THIS EXISTS. A correction is a diff keyed by event id, so the id is a
 * contract between a Python module and a TypeScript one, and nothing else in
 * this repository holds the two sides together. `migrateCorrectionIds` in
 * `correction.ts` decides what is an old id by counting dash-separated
 * segments, which is only sound while the reader keeps building ids the way
 * this file asserts it does. The day the reader puts a dash in a new place, the
 * migration starts mangling ids and the singer's corrections stop landing,
 * silently. This is the test that fails first instead.
 *
 * WHAT CAN AND CANNOT BE ASSERTED HERE, the same honest boundary
 * `page-reader.driver.test.ts` draws: the id construction lives in Python, run
 * under Pyodide in a Worker, and vitest cannot execute it. What vitest CAN do
 * is read the source and hold its shape. The behaviour on real pages is
 * measured in the harness instead and reported in the N.97 memo: 1,118 ids over
 * 25 corpus pages, 47 of them carrying the collision suffix, zero duplicates.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/** The canonical reader. `apps/web/static/reader/` is a generated copy of it. */
const SOURCE = new URL('../../../../../../tools/e16-harness/reader/run_page2.py', import.meta.url);
const ENVELOPE = new URL('../../../../../../tools/e16-harness/reader/envelope.py', import.meta.url);
const SERVED = new URL('../../../../static/reader/run_page2.py', import.meta.url);

const runPage2 = readFileSync(SOURCE, 'utf8');
const envelope = readFileSync(ENVELOPE, 'utf8');

/** The one line that builds an id. */
function idExpression(): string {
	const m = runPage2.match(/nd = dict\(id=\((.*?)\),/s);
	if (!m) throw new Error('run_page2.py no longer builds its id in a dict(id=(...)) expression');
	return m[1];
}

describe('N.97 the reader builds ids from measure and x', () => {
	it('names the measure and the x, and nothing else', () => {
		const expr = idExpression();
		expect(expr).toContain('f"r{mi}-{e[\'x\']}"');
		expect(expr).toContain("f\"r{mi}-{e['x']}-{ord_n}\"");
	});

	it('keeps the onset out of the id, which is the whole point of the re-key', () => {
		// The onset is a running sum over the measure's preceding events, so an
		// id carrying it is renamed whenever the event population changes -- and
		// N.97 changes the event population on purpose.
		const expr = idExpression();
		expect(expr).not.toContain('onset');
		expect(expr).not.toContain('na-na');
	});

	it('still emits the onset as its own field, which the re-key never touched', () => {
		expect(runPage2).toMatch(/onset=onset_field/);
	});

	it('gives the second and later event at one x a stable ordinal, from 2 up', () => {
		expect(runPage2).toMatch(/ord_n = x_ordinal\.get\(e\['x'\], 0\) \+ 1/);
		expect(idExpression()).toMatch(/ord_n == 1/);
	});

	it('counts the ordinal in x-sorted order, which is the order the loop walks', () => {
		const loop = runPage2.slice(
			runPage2.indexOf('segev = sorted('),
			runPage2.indexOf('msum[mi] =')
		);
		expect(loop).toMatch(/segev = sorted\(\[e for e in ev if lo <= e\['x'\] < hi\], key=lambda e: e\['x'\]\)/);
		// The counter is reset per measure, so an ordinal never carries across a
		// barline: two events at one x in DIFFERENT measures both get no suffix.
		const resetAt = loop.indexOf('x_ordinal = {}');
		const useAt = loop.indexOf('x_ordinal.get(');
		expect(resetAt).toBeGreaterThan(-1);
		expect(useAt).toBeGreaterThan(resetAt);
	});
});

describe('N.97 the id survives the page-to-piece remap', () => {
	it('rewrites only the measure prefix, so an x and an ordinal come through whole', () => {
		// envelope.py renumbers page 2 and later from page-local measures to
		// piece-global ones by rewriting the leading `r{local}-`. Everything
		// after that first dash is carried across untouched, which is what keeps
		// `r{mi}-{x}-{n}` intact.
		expect(envelope).toMatch(/old_prefix = f"r\{local_mi\}-"/);
		expect(envelope).toMatch(/nd\['id'\] = f"r\{global_mi\}-" \+ nd\['id'\]\[len\(old_prefix\):\]/);
	});
});

describe('the served reader is the reader the harness runs', () => {
	it('serves run_page2.py byte for byte, where the generated copy exists', () => {
		// `apps/web/static/reader/` is generated by scripts/copy-reader.mjs at dev
		// and build and is gitignored, so a clean checkout has not got it yet.
		// Skipping it there beats failing on a file nobody was asked to make.
		if (!existsSync(fileURLToPath(SERVED))) return;
		expect(readFileSync(SERVED, 'utf8')).toBe(runPage2);
	});
});
