/**
 * N.173, the gates on real songs: what Markup's box prints for Mitton's
 * voice on the six Sunless songs, and what each gate dropped. Revision r5:
 * gate 2 strict, no page limit.
 *
 * The chain is `MarkupPane.svelte`'s: the reading octave, the vowel resolver on
 * verse 1, the analysis on the performance-order score with the advice
 * post-pass, `buildWatchList`, then `applyGates` and `gatedLines`. Brief:
 * `docs/sessions/brief-code-watch-band-says-less_r1_2026-09-28.md`.
 *
 * The output quotes the box's lines, which carry sung words, so it goes to
 * the gitignored `apps/web/test-results/`, never to `out/` (lyric text stays
 * out of the repository).
 *
 * Run from the repository root:
 *   pnpm --filter @ilya/web exec vitest run --config ../../tools/n168-frequency-run/gates-trial.config.ts
 */

import { test } from 'vitest';
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
	MnxScoreParser,
	analyzeScore,
	foldDictionMarks,
	noteConditions,
	resolveVocalReadingOctave,
	scoreInPerformanceOrder,
	shiftVocalOctave,
	type Pitch,
	type VoiceProfileSnapshot,
} from '@ilya/score-parser';
import { setStressDictionary, setSingerSupplement } from '@ilya/phonology';
import { setGlossDictionary } from '@ilya/dictionary';
import { setBlurbData } from '@ilya/blurb';
import { installHomographEntries } from '$lib/loader';
import { buildUnderlayResolvers } from '$lib/score/vowel-resolver';
import { musxToMnxJson } from '../e16-harness/src/denigma-convert';
import { buildWatchList, watchBandLines } from '$lib/analysis/watchlist';
import { resolveAdvice } from '$lib/analysis/advice-resolver';
import { applyGates, gatedLines, GATE_DEFAULTS, type GatedEntry } from '$lib/analysis/gates';
import { advisedKinds } from './gates-trial.kinds';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '../..');
const FINALE = path.join(os.homedir(), 'Documents', 'Finale Files');

const P = (step: Pitch['step'], octave: number, alter = 0): Pitch => ({ step, octave, alter });

/** Mitton, as `frequency-run.run.ts` carries him (fR1 from `modification-engine.test.ts:21-24`). */
const MITTON: VoiceProfileSnapshot = {
	fR1: { i: 296, e: 381, ɪ: 393, ɨ: 404, u: 346, o: 489, ɛ: 577, ʌ: 616, ɑ: 617, a: 711 },
	fR2: { i: 1705, e: 1532, ɪ: 1600, ɨ: 1100, u: 804, o: 826, ɛ: 1311, ʌ: 1167, ɑ: 1013, a: 1113 },
	range: { lowest: P('A', 2), highest: P('E', 4) },
	passaggio: { primo: P('A', 3, -1), secondo: P('D', 4, -1) },
	label: 'Mitton, low male voice',
};

/** The six Sunless songs, in cycle order. */
const SONGS = readdirSync(FINALE)
	.filter((f) => /^Mussorgsky - Sunless 0[1-6] - .*\.musx$/.test(f))
	.sort()
	.map((file) => ({ id: `Sunless ${file.match(/Sunless (\d\d)/)![1]}${file.includes(' 04 ') ? ', «Скучай»' : ''}`, file }));

function loadDictionary(): void {
	const data = path.join(repo, 'apps/web/static/data');
	const manifest = JSON.parse(readFileSync(path.join(data, 'dictionary-manifest.json'), 'utf8'));
	const dictionary: Record<string, any> = {};
	for (const file of manifest.files as string[]) {
		for (const line of readFileSync(path.join(data, file), 'utf8').split(/\r?\n/)) {
			if (!line.trim()) continue;
			try {
				const [word, entry] = JSON.parse(line);
				if (entry.e !== undefined || entry.f !== undefined) entry.g = { en: entry.e || '', fr: entry.f || '' };
				dictionary[word] = entry;
			} catch {
				// as loader.ts
			}
		}
	}
	setStressDictionary(dictionary);
	setSingerSupplement(JSON.parse(readFileSync(path.join(data, 'singer-supplement.json'), 'utf8')));
	setGlossDictionary(dictionary);
	setBlurbData(JSON.parse(readFileSync(path.join(data, 'blurb-composer.json'), 'utf8')));
	installHomographEntries(dictionary, JSON.parse(readFileSync(path.join(data, 'homographs.json'), 'utf8')));
}

const describe = (g: GatedEntry) =>
	`bar${g.bars.length > 1 ? 's' : ''} ${g.bars.join(', ')}; ${g.entry.kinds.join('+')} [${g.entry.vowel}]${g.entry.advice ? `; advice ${g.entry.advice.action}` : '; no advice, rare'}; stakes ${g.stakes} = ${g.demands.length} (${g.demands.join(', ') || 'none'}) × ${1 + g.weights.length} (1${g.weights.map((w) => ` + ${w}`).join('')})`;

test('N.173 gates trial', async () => {
	loadDictionary();
	const md: string[] = [
		'# N.173 gates trial: what the box prints',
		'',
		`Voice: ${MITTON.label}, range A2 to E4, passaggio A♭3 to D♭4. Gate 2 strict, stakes threshold ${GATE_DEFAULTS.stakesThreshold}, no page limit (Revision r5). Generated by \`gates-trial.run.ts\`.`,
		'',
	];
	for (const song of SONGS) {
		const mnx = await musxToMnxJson(path.join(FINALE, song.file));
		const parsed = foldDictionMarks((await new MnxScoreParser().parse({ format: 'mnx', data: JSON.parse(mnx), sourcePath: song.file })).score).score;
		const shift = resolveVocalReadingOctave(parsed, MITTON.range);
		const readingScore = shift !== 0 ? shiftVocalOctave(parsed, shift) : parsed;
		const analysisScore = scoreInPerformanceOrder(readingScore).score;
		const vowel = buildUnderlayResolvers(readingScore, 1).vowel;
		const analyzed = resolveAdvice(analyzeScore(analysisScore, MITTON, vowel));
		const watchList = buildWatchList(readingScore, analyzed, 1, { analysisScore, profile: MITTON, resolver: vowel });
		const notes = noteConditions(analysisScore, MITTON, analyzed.events, { vowelForEvent: vowel, barsFrom: readingScore }).notes;
		const r = applyGates({ watchList, notes, profile: MITTON });

		md.push(`## ${song.id}`, '');
		md.push(`Before the gates the band printed ${watchBandLines(watchList.entries, 'en').length} lines. After: ${r.shown.length}.`, '');
		const sweep = [1, 2, 3, 4, 6].map((t) => `${t}: ${applyGates({ watchList, notes, profile: MITTON, defaults: { ...GATE_DEFAULTS, stakesThreshold: t } }).shown.length}`);
		md.push(`Entries printed at each stakes threshold: ${sweep.join('; ')}.`, '');
		md.push(`Kinds on the band before the gates: ${advisedKinds(watchList.entries)}.`, '');
		md.push(`Gate 1, the piece fits: ${r.fits ? 'yes' : `no; ${r.notFit.length} entries withheld`}.`, '');
		for (const lang of ['en', 'fr'] as const) {
			md.push(`**The box, ${lang === 'en' ? 'English' : 'French'}:**`, '');
			const lines = gatedLines(r.shown, lang);
			md.push(...(lines.length ? lines.map((l) => `- ${l}`) : ['- (the box does not render)']), '');
		}
		md.push('**Why each printed:**', '', ...r.shown.map((g) => `- ${describe(g)}`), '');
		md.push(`**Gate 2 dropped ${r.noOffer.length}** (no sourced thing to try, and no kind rare here): ${summarize(r.noOffer.map((e) => `${e.bar} ${e.kinds.join('+')}`))}`, '');
		md.push(`**Gate 3 dropped ${r.lowStakes.length}** (stakes under ${GATE_DEFAULTS.stakesThreshold}): ${summarize(r.lowStakes.map(({ entry, stakes }) => `${entry.bar} ${entry.kinds.join('+')} (${stakes})`))}`, '');
		md.push(`**Gate 4 folded ${r.folded.length}** into another entry's line: ${summarize(r.folded.map((e) => `${e.bar} ${e.kinds.join('+')}`))}`, '');
	}
	const outDir = path.join(repo, 'apps/web/test-results/n173-gates-trial');
	mkdirSync(outDir, { recursive: true });
	writeFileSync(path.join(outDir, 'gates-trial.md'), md.join('\n'));
	console.log(md.join('\n'));
});

function summarize(items: string[]): string {
	return items.length ? items.join('; ') : 'none';
}
